{% set name = "django-pint" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-pint-{{ version }}.tar.gz
  sha256: dbcbe5143cc8feb83e03ce8e4a517dc370f918bbb96343c677ad84cebe7dc3b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - pint >=0.16

test:
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/CarliJoy/django-pint/
  summary: '"Quantity Field for Django using pint library for automated unit conversions"'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alexpilot11
    - BryanAke
